apiVersion: v2
name: gotrade-n8n
description: Gotrade's Helm chart to deploy self-hosted n8n workflow automation

type: application

version: {{.Env.VERSION}}

appVersion: "1.72.0"

dependencies:
  - name: postgresql
    version: 18.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 23.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
