apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  database-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.redis.enabled) .Values.externalRedis.password }}
  redis-password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}
  encryption-key: {{ .Values.n8n.encryptionKey | b64enc | quote }}
