name: "CI/CD"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  Pre-commit:
    runs-on: [alicloud-arm64]
    steps:
      - uses: tr8team/actions.setup-nix@eeb5621ccca43c73f4585ca60d684663af1c1fdf # tr8 fork: installer-binary + no diagnostics
        with:
            namespacelabs: 'false'
            installer-binary: /opt/nix-installer/nix-installer

      - name: Run Pre-commit checks
        run: nix develop .#ci -c scripts/ci/pre-commit.sh
        env:
          NIXPKGS_ALLOW_UNFREE: "1"

  Release:
    needs:
      - Pre-commit
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on: [alicloud-arm64]
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: tr8team/actions.setup-nix@eeb5621ccca43c73f4585ca60d684663af1c1fdf # tr8 fork: installer-binary + no diagnostics
        with:
            namespacelabs: 'false'
            installer-binary: /opt/nix-installer/nix-installer
        with:
          token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          fetch-depth: 0

      - name: Remove GitHooks
        run: rm ./.git/hooks/* || true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          NIXPKGS_ALLOW_UNFREE: "1"
        run: nix develop .#cd -c scripts/ci/release.sh
