name: "CI/CD"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  Pre-commit:
    runs-on:
      - nscloud-ubuntu-22.04-arm64-2x4-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-n8n-helm-nix-store-cache
    steps:
      - uses: AtomiCloud/actions.setup-nix@v2

      - name: Run Pre-commit checks
        run: nix develop .#ci -c scripts/ci/pre-commit.sh
        env:
          NIXPKGS_ALLOW_UNFREE: "1"

  Release:
    needs:
      - Pre-commit
    name: Release
    if: github.ref == 'refs/heads/main'
    runs-on:
      - nscloud-ubuntu-22.04-arm64-2x4-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-n8n-helm-nix-store-cache
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: AtomiCloud/actions.setup-nix@v2
        with:
          token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          fetch-depth: 0

      - name: Remove GitHooks
        run: rm ./.git/hooks/* || true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          NIXPKGS_ALLOW_UNFREE: "1"
        run: nix develop .#cd -c scripts/ci/release.sh
